### ISSUE TITLE
Button to close all tabs

### ISSUE THREAD

**Issue by digitaltim-de** [caioricciuti/ch-ui#11]
### Idea Statement

Closing all tabs one by one is sometimes very hard

### Feature implementation brainstorm

Sometimes i have so many tabs, it will be easier for us, if you add an button to close all the tabs and refresh the states and maybe u add an Environment to disable the "Alert confirmation" user based :)

**Comment by caioricciuti** [comment]
Added on commit 4a6446cf9f7401265971c2cad4c455a9f7b638fb
