### ISSUE TITLE
Connection to clickhouse reports 501 not implemented

### ISSUE THREAD

**Issue by gyj-hub** [caioricciuti/ch-ui#24]
### Environment

Docker

### How did you encounter the bug?

I run the docker image using the following command:

_root@harbor 20240926]# docker run --name ch-ui -d -p 5521:5521 ghcr.io/caioricciuti/ch-ui:latest
a3d3bcefcf123926002dda12cb8469cdca0071d8a6427f01a0e7f8b6ef72f449
[root@harbor 20240926]#_ 

I use a browser to visit http://192.168.25.5:5521/, then I enter the corresponding information and click submit, the page does not change, no success, it still stays on the current page. I press F12 to open the debug window, and I see the following information:

Request URL: http://192.168.25.11:8123/
Request method: OPTIONS
Status code: 501 Not Implemented
Remote address: 192.168.25.11:8123
Reference site policy: strict-origin-when-cross-origin

![20240926134145](https://github.com/user-attachments/assets/66a0a558-0b09-4c38-b6b5-f7d7a1fd2a75)

The docker container does not provide much log information, as follows:

_[root@harbor 20240926]# docker logs ch-ui
Environment variables injected successfully
 WARN  Checking for updates failed (use `--debug` to see full error)
 INFO  Accepting connections at http://localhost:5521
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 GET /settings
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 Returned 304 in 37 ms
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 GET /assets/index-CZqaCBJ4.js
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 GET /assets/index-gXmAc3Iu.css
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 Returned 304 in 4 ms
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 Returned 304 in 22 ms
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 GET /vite.png
 HTTP  9/26/2024 5:32:07 AM 192.168.25.1 Returned 304 in 2 ms
[root@harbor 20240926]#_

### What did you expect?

I expect ch-ui to be able to connect to the click house database normally, and use ch-ui normally.

### Actual Result

ch-ui is not connected to the click house database and cannot be used normally.

**Comment by caioricciuti** [comment]
Hey, can you try the following: 

### Network 

I see you're trying to connect to `192.168.25.11:8123`, so: 

- Ensure the IP address (192.168.25.11:8123) is correct and the port (8123) is open.
- Try pinging the IP address from the machine running the UI app.
- Check if any firewalls are blocking the connection.


###  Cors & Click house config 

- Try to connect using `http://127.0.0.1:8123` or `http://localhost:8123` (If the instance is running on your machine)...
- Make sure you have the right configuration of your click-house instance see #8... 
- Run `curl "http://192.168.25.11:8123/?query=SELECT%201"` Do you see any results? 

### Misc 

- Check ClickHouse logs (you can find something there).

**Comment by gyj-hub** [comment]
I have completely turned off the firewall on these hosts:
`
[root@clickhouse2 ~]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@clickhouse2 ~]#
`

I saw in the clickhouse log that the account or password is incorrect:

_2024.09.26 14:42:30.968896 [ 1468 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:58207, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 14:42:30.979440 [ 1466 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:58208, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 14:42:30.985203 [ 12324 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:58209, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 14:42:30.985339 [ 12324 ] {} <Trace> DynamicQueryHandler: Request URI: /?query_id=35a27b47-1674-4293-9aec-6c52205676b2
2024.09.26 14:42:30.985424 [ 1468 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:58210, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 14:42:30.985438 [ 12324 ] {} <Trace> ContextAccess (default): Settings: readonly=0, allow_ddl=true, allow_introspection_functions=false
2024.09.26 14:42:30.985457 [ 12324 ] {} <Trace> ContextAccess (default): List of all grants: GRANT SHOW, SELECT, INSERT, ALTER, CREATE, DROP, TRUNCATE, OPTIMIZE, KILL QUERY, SYSTEM, dictGet, SOURCES ON *.*
2024.09.26 14:42:30.985473 [ 1468 ] {} <Trace> DynamicQueryHandler: Request URI: /?query_id=01191124-0fc3-4a00-95d7-0d55b0acd86a
2024.09.26 14:42:30.985658 [ 12324 ] {} <Error> DynamicQueryHandler: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. ? @ 0x15863e76 in /usr/bin/clickhouse
3. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1647ba44 in /usr/bin/clickhouse
4. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1648088b in /usr/bin/clickhouse
5. Poco::Net::HTTPServerConnection::run() @ 0x18cfafb3 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
10. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.9.3.45 (official build))
2024.09.26 14:42:30.985711 [ 1468 ] {} <Error> DynamicQueryHandler: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. ? @ 0x15863e76 in /usr/bin/clickhouse
3. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1647ba44 in /usr/bin/clickhouse
4. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1648088b in /usr/bin/clickhouse
5. Poco::Net::HTTPServerConnection::run() @ 0x18cfafb3 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
10. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.9.3.45 (official build))_

But I can absolutely guarantee that the account and password are correct:
`[root@clickhouse2 ~]# cat /etc/clickhouse-server/users.xml|grep '/password>'
                 Example: <password>qwerty</password>.
            <password>Cmcc_chengdu2o23</password>
[root@clickhouse2 ~]#
`

The account I use is the default account: default。

**Comment by caioricciuti** [comment]
The default user in clickhouse does not have a password... you can try it without password?

**Comment by caioricciuti** [comment]
The default user in clickhouse does not have a password... you can try it without password?

**Comment by gyj-hub** [comment]
No, it won’t work.
```bash
[root@harbor ~]# docker rm -f ch-ui
ch-ui
[root@harbor ~]# docker run --name ch-ui -h ch-ui -p 5521:5521 \
>   -e VITE_CLICKHOUSE_URL=http://192.168.25.12:8123 \
>   -e VITE_CLICKHOUSE_USER=default \
>   ghcr.io/caioricciuti/ch-ui:latest
Environment variables injected successfully
 WARN  Checking for updates failed (use `--debug` to see full error)
 INFO  Accepting connections at http://localhost:5521
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 GET /settings
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 Returned 200 in 46 ms
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 GET /assets/index-CZqaCBJ4.js
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 GET /assets/index-gXmAc3Iu.css
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 Returned 304 in 8 ms
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 Returned 304 in 39 ms
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 GET /vite.png
 HTTP  9/26/2024 7:21:02 AM 192.168.25.1 Returned 304 in 2 ms


```
clickhouse的日志跟之前一样：
```bash
2024.09.26 15:22:08.447837 [ 1468 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:59293, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 15:22:08.458242 [ 12324 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:59294, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 15:22:08.461599 [ 1466 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:59295, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 15:22:08.461729 [ 1466 ] {} <Trace> DynamicQueryHandler: Request URI: /?query_id=f2971bd0-d912-4ce3-8022-c36e4e7bcee4
2024.09.26 15:22:08.461895 [ 1466 ] {} <Error> DynamicQueryHandler: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. ? @ 0x15863e76 in /usr/bin/clickhouse
3. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1647ba44 in /usr/bin/clickhouse
4. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1648088b in /usr/bin/clickhouse
5. Poco::Net::HTTPServerConnection::run() @ 0x18cfafb3 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
10. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.9.3.45 (official build))
2024.09.26 15:22:08.461993 [ 1466 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2024.09.26 15:22:08.467077 [ 1468 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: OPTIONS, Address: 192.168.25.1:59296, User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0, Content Type: , Transfer Encoding: identity
2024.09.26 15:22:08.467257 [ 1468 ] {} <Trace> DynamicQueryHandler: Request URI: /?query_id=a7be9f73-3de6-4c56-8906-d6e0f82dcade
2024.09.26 15:22:08.467517 [ 1468 ] {} <Error> DynamicQueryHandler: Code: 516, e.displayText() = DB::Exception: default: Authentication failed: password is incorrect or there is no user with such name, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e1b360 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe736dad in /usr/bin/clickhouse
2. ? @ 0x15863e76 in /usr/bin/clickhouse
3. DB::HTTPHandler::processQuery(DB::Context&, Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x1647ba44 in /usr/bin/clickhouse
4. DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) @ 0x1648088b in /usr/bin/clickhouse
5. Poco::Net::HTTPServerConnection::run() @ 0x18cfafb3 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x18d391cb in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x18d3965b in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x18eb8136 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x18eb3530 in /usr/bin/clickhouse
10. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.9.3.45 (official build))
```

**Comment by caioricciuti** [comment]
Could you make it work, was investigating and I don't see how this is a problem of the UI tool, I believe you have something off on your clickhouse config (instance) so the UI cannot connect, the `500` errors on the app means a problem with the server, since the UI does not have a server and connects directly to your Click House instance there's no much we can do thought the UI... Also have you consider to update your click house version? 

`(version 20.9.3.45 (official build))` consider updating...
