### ISSUE TITLE
crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by fidiego** [caioricciuti/ch-ui#29]
### Environment

Docker

### How did you encounter the bug?

1. Run Docker container
2. Access the ui on a non-https connection
3. Page loads but w/ an error `crypto.randomUUID is not a function`

### What did you expect?

Expected a page w/out an error and the ability to proceed to the app. 

### Actual Result

<img width="816" alt="image" src="https://github.com/user-attachments/assets/0f5cc876-db81-4ce8-89c1-b33306213634">

**Comment by frivollier** [comment]
I am experiencing the same issue with both https or http interfaces.

**Comment by caioricciuti** [comment]
Hello @frivollier and @fidiego, thank you both for reporting the issue, I tried to reproduce the error and couldn't. What browser are you using? This method `cypto.randomUUID` should be available in most browsers. I'm looking into it, let me know the browser please so I can try to reproduce it...

**Comment by frivollier** [comment]
I can confirm that running a container locally and connecting to a locally hosted clickhouse work fine. 
The issue arises when connection to a remotely hosted clickhouse.
I have checked the port and credentials with another SQL client, and it is fine. 
![image](https://github.com/user-attachments/assets/b822945e-e9dc-4cda-9b9d-46e30563f56a)

**Comment by fidiego** [comment]
To add some context, I access the ch-ui via the browser on a non-https connection. ch-ui is configured to connect to a clickhouse cluster via a k8s service also on a non-https connection. this is because these services are only available from within a meshnet so we are not concenred about ssl. this leads me to suspect this function is not made available in my sessions/windows because i'm not using HTTPS; as per the info at the top of [the MDN page on the topic](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID).

**Comment by netadvanced** [comment]
@fidiego Thank you for reporting this issue.  I had the same problems and following this thread I managed to figure out that indeed I wasn't using HTTPS. Configured Traefik and all is good now. 👍🏼🥳

**Comment by caioricciuti** [comment]
Fixed :) Added to main, please let me know if solve on release `Release v1.5.5` 
```js
// Polyfill for crypto.randomUUID if not available
if (typeof crypto.randomUUID !== "function") {
  crypto.randomUUID = function () {
    return '10000000-1000-4000-8000-100000000000'.replace(/[018]/g, c =>
      (parseInt(c) ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> parseInt(c) / 4).toString(16)
    ) as `${string}-${string}-${string}-${string}-${string}`;
  };
}
```

**Comment by fidiego** [comment]
works great, thanks @caioricciuti !
