### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by MeisterLone** [caioricciuti/ch-ui#3]
### Environment

NPM build

### How did you encounter the bug?

All I get is a node error in the corner of the browser when I try to connect:
Server status check failed: crypto.randomUUID is not a function

This happens for both installed and docker versions. 

```
root@ubuntu:~/ch-ui# node -v
v20.14.0
root@ubuntu:~/ch-ui# npm -v
10.7.0
root@ubuntu:~/ch-ui#
```

### What did you expect?

.

### Actual Result

.

**Comment by caioricciuti** [comment]
Hello @MeisterLone, I was not able to reproduce the issue on my machine, so not quite sure on where to start investigating... The thing is that the message you said you get as an error "Server status check failed" comes from the following function: 

```js 
//src/providers/ClickHouseContext.jsx

const checkServerStatus = useCallback(async () => {
    try {
      const availability = await clickHouseClient.current.ping();
      if (!availability.success) {
        toast.error("ClickHouse server is not available");
      }
      const versionResponse = await clickHouseClient.current.query({
        query: "SELECT version()",
        format: "JSONEachRow",
      });
      const versionData = await versionResponse.json();
      setVersion(versionData[0]["version()"] || "Unknown");
      setIsServerAvailable(true);
      toast.success("ClickHouse server is available");
    } catch (error) {
      setIsServerAvailable(false);
      setError(`Server status check failed: ${error.message}`);
      setVersion("-");
      toast.error(`Server status check failed: ${error.message}`);
    }
  }, []);
```

What I've done is to create a `Polyfill for crypto.randomUUID`... Maybe it works, please let me know... 

Also please make sure your click-house server/instance is running correctly, you can open your terminal and run the following: 

```curl 
curl -u <username>:<password> 'http://<clickhouse_server_url>:<port>/?query=SELECT+version()'
```

the result should be something like: 

![image](https://github.com/caioricciuti/ch-ui/assets/63287675/dc65628c-aac1-4db2-99d7-becba96a38e7)

**Comment by MeisterLone** [comment]
Awesome! It works now. Thank you sir

**Comment by MeisterLone** [comment]
Awesome! It works now. Thank you sir
