### ISSUE TITLE
Change docker-compose.yml env vars to $vars

### ISSUE THREAD

**Issue by oalexdoda** [caioricciuti/ch-ui#35]
### Environment

Docker

### How did you encounter the bug?

When trying to load this in Coolify (or a place where you can't edit the docker compose file), it breaks because of the hard-coded values. I think this should be updated so that it automatically references env vars.

![image](https://github.com/user-attachments/assets/60baa585-2923-4727-99da-8a9e68131211)

i.e. `VITE_CLICKHOUSE_URL=$VITE_CLICKHOUSE_URL`

### What did you expect?

Dynamic env vars

### Actual Result

Static env vars

### Browser

Chrome

### Browser Version

-

### Version

-

**Comment by caioricciuti** [comment]
done!
