### ISSUE TITLE
Unable to create table with Engine ReplicatedMergeTree

### ISSUE THREAD

**Issue by prasathsekar** [caioricciuti/ch-ui#36]
### Idea Statement

While creating a table there is an option for choosing Database Engine. In that ReplicatedMergeTree Option not Available

**Comment by caioricciuti** [comment]
Hey, I'll take a look into that, thanks for pointing out!

**Comment by caioricciuti** [comment]
Thank you for pointing out the "Database Engine" It's the Table engine... 

![Screenshot 2024-11-08 at 11 58 18](https://github.com/user-attachments/assets/2584fa71-6fa3-4897-91b8-a384b47659e4)

![Screenshot 2024-11-08 at 11 53 53](https://github.com/user-attachments/assets/305dc983-19a2-4229-bc35-d3d851a570b5)

For me, it works... Are you on the last version? I'll release the typo fix on the next push! :)

**Comment by prasathsekar** [comment]
Your screenshot refers to ReplacingMergeTree, but I am looking to create a ReplicatedMergeTree. Both are not same.

**Comment by caioricciuti** [comment]
True, sorry I just added!
