### ISSUE TITLE
Can't create temporary table

### ISSUE THREAD

**Issue by pirsquare** [caioricciuti/ch-ui#38]
### Environment

NPM build

### How did you encounter the bug?

`
CREATE TEMPORARY TABLE temp_records AS
(
  select * from algotrading.ticker_details limit 5
)`
![screenshot-5_223_43_26_4173-2024_11_07-10_01_24](https://github.com/user-attachments/assets/36200906-c6cb-41f3-a965-4ac3150448fd)

Error
Unexpected end of JSON input

### What did you expect?

New Table

### Actual Result

Unexpected end of JSON input

### Browser

Chrome

### Browser Version

Version 130.0.6723.93

### Version

Server version: 24.10.1.2812
[v1.5.9](https://github.com/caioricciuti/ch-ui/releases/tag/v1.5.9)

**Comment by caioricciuti** [comment]
<img width="639" alt="Screenshot 2024-11-10 at 10 49 25" src="https://github.com/user-attachments/assets/a17b7ae6-b509-4f81-8019-c75cbb41d7b4">

Now we can I'll release this fix :)
