### ISSUE TITLE
Spelling mistake in the readme file. 

### ISSUE THREAD

**Issue by mammod2** [caioricciuti/ch-ui#4]
### Environment

Docker

### How did you encounter the bug?

just a minor spelling mistake in the read me file.

### What did you expect?

'Using Docker'

### Actual Result

![Screenshot 2024-06-21 at 3 59 06 PM](https://github.com/caioricciuti/ch-ui/assets/59960409/44978184-4f6e-4227-92ff-114647a2d5e2)

its written as Using using Docker

**Comment by caioricciuti** [comment]
Fixed, thank you @mammod2 :)
