### ISSUE TITLE
clickhouse clusters running behind nginx: cannot use path based host

### ISSUE THREAD

**Issue by joegerges** [caioricciuti/ch-ui#40]
i have an nginx proxy running on https://clickhouse-proxy.domain.team where it routes location /clickhouse-{cluster_name} to the correct cluster (one nginx for all clickhouse clusters that are running in k8s), proxy config:

```
    location ~ ^/(clickhouse-[a-zA-Z0-9\-]+) {
        set $service_name $1;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Authorization $http_authorization;
        proxy_read_timeout 120;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        # Use the captured service name to dynamically construct the proxy URL
        proxy_pass http://$service_name.ch.svc.cluster.local:8123;
    }
```

Selecting https://clickhouse-proxy.domain.team/clickhouse-testcluster as clickhouse host will result in trying to query https://clickhouse-proxy.domain.team with database=clickhouse-testcluster in the filter string. Is there a way around this?

If not, wouldn't adding a Database optional field in the login UI and support full path hosts like tabix.io make more sense? 

I'm currently trying to migrate from tabix UI (where my config is working) to yours as it seems much cleaner, so your help is appreciated.

**Comment by caioricciuti** [comment]
Heyy @joegerges I'm sorry to take this long to get back to you...  I've made some changes and hopefully, it helps you to solve the connection issue.

I've changed a bit the connection settings: 

<img width="712" alt="image" src="https://github.com/user-attachments/assets/e9db934a-6d01-493c-9e00-df23c3715867">

Let me know if you can connect this way... Thanks!

**Comment by joegerges** [comment]
hello! @caioricciuti thank you for your reply.

I've deployed the new version and tried to test it but i still cant seem to connect:

<img width="909" alt="image" src="https://github.com/user-attachments/assets/b5145d7d-36a0-4184-afc0-459b235b8bc7">

the resulting query becomes:

https://clickhouse-tabix.noonstg.team/?query_id=d3cd65a6-0e30-433f-9913-2b9b83999d1b&max_result_rows=0&max_result_bytes=0&result_overflow_mode=break&database=clickhouse-svctest1%2Fclickhouse-svctest1

where i think it needs to be something like this:

https://clickhouse-tabix.noonstg.team/clickhouse-svctest1?query_id=d3cd65a6-0e30-433f-9913-2b9b83999d1b&max_result_rows=0&max_result_bytes=0&result_overflow_mode=break

PS: both my nginx and ch-ui are running on the same domain to avoid cors.

**Comment by joegerges** [comment]
btw not sure if this helps, but i noticed whenever i refresh the ch-ui page, it takes the custom path and appends it to the host in the ClickHouse Host section in the frontend.

**Comment by caioricciuti** [comment]
It's hard for me to test since I don't quite have the same config... can you try to put a /<Path>?

**Comment by joegerges** [comment]
to debug this locally i ran the ui (without any clickhouse cluster or anything just to check the network tab):

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/7d3096ea-5e6f-4049-ace0-79724e76876e">

you can see the call that is being made after the "save and connect" button is clicked is the following: http://localhost:5521/?query_id=b09dd018-dcfa-4926-821c-aaad6d71b4bc&max_result_rows=0&max_result_bytes=0&result_overflow_mode=break&database=clickhouse-test%2Fclickhouse-test

The desired api call shoud have the host as: http://localhost:5521/clickhouse-test? instead of http://localhost:5521/?

and i can see that the database being queried is database=clickhouse-test%2Fclickhouse-test not sure how its happening. Im not really familiar with js.

**Comment by caioricciuti** [comment]
thank you for all info, I'll investigate that and get back yo you asap!

**Comment by joegerges** [comment]
@caioricciuti i think this should help: https://clickhouse.com/docs/en/integrations/javascript

there's a pathname variable in the createClient function for clickhouse in case of proxy use

**Comment by joegerges** [comment]
Any updates on this? @caioricciuti

**Comment by caioricciuti** [comment]
Hey @joegerges, I'm sorry, but nothing yet. I'll do my best to find time tomorrow to go over this. I appreciate your patience, thanks!

**Comment by joegerges** [comment]
hey @caioricciuti,

I was able to clone the repo and fix the issue (built the image, deployed and connected to my clickhouse clusters).
I didn't have write access to the repo to submit a PR so here's my git diff results (its a 2 line change):

jgerges@IT-C02YH0NHJG5J ch-ui % git diff
diff --git a/src/features/workspace/editor/monacoConfig.ts b/src/features/workspace/editor/monacoConfig.ts
index 4803078..ae9293f 100644
--- a/src/features/workspace/editor/monacoConfig.ts
+++ b/src/features/workspace/editor/monacoConfig.ts
@@ -24,10 +24,13 @@ function initializeClickHouseClient(
     typeof credential.host === "string" &&
     credential.host.trim() !== "" &&
     typeof credential.username === "string" &&
-    credential.username.trim() !== ""
+    credential.username.trim() !== "" &&
+    typeof credential.customPath === "string" &&
+    credential.customPath.trim() !== ""
   ) {
     client = createClient({
       url: credential.host,
+      pathname: credential.customPath,
       username: credential.username,
       password: credential.password || "", // Allow empty password
     });
diff --git a/src/store/slices/core.ts b/src/store/slices/core.ts
index e79215a..90fa18c 100644
--- a/src/store/slices/core.ts
+++ b/src/store/slices/core.ts
@@ -57,6 +57,7 @@ export const createCoreSlice: StateCreator<
             
             const client = createClient({
                 url: connectionUrl,
+                pathname: credential.customPath,
                 username: credential.username,
                 password: credential.password || "",
                 clickhouse_settings: get().clickhouseSettings,
                 
Please do let me know if this breaks anything from your end, but it looks fine to me!

**Comment by caioricciuti** [comment]
Heyyyy, that's why we can go forward with the app, I'll check this afternoon and if it works I'll create a new release today! Thank you for trying and more than that, to make our app better!

**Comment by joegerges** [comment]
No worries at all!

sorry I forgot to mention as well, in the Settings.tsx file we also need to remove the part where we append the customPath to the host as it’s not needed anymore :)

**Comment by caioricciuti** [comment]
Hey, can you test it? I just created a release. Please let me know :)

**Comment by joegerges** [comment]
hey @caioricciuti,

just tested and all works from my end with the proxy setup. I was able to connect, create db, tables, insert and fetch data.

Thanks for the release!
