### ISSUE TITLE
Improve table detail presentation 

### ISSUE THREAD

**Issue by synack-ppetruneac** [caioricciuti/ch-ui#44]
### Idea Statement

1. Format the total rows from a table. 6552590 > 6,552,590 
2. Fix `Last modified` - I always get `Invalid Date` 
 ![Screenshot 2024-11-28 at 14 27 11](https://github.com/user-attachments/assets/575bc05d-b68a-4d85-8a52-823806822dbe)
3. Add details on the table schema in the `Details` view. something like BigQuery: 
![Screenshot 2024-11-28 at 14 28 56](https://github.com/user-attachments/assets/7f10f39e-cb50-417e-914e-d669b6e2ff85)

This is what I'm running on: 
> ClickHouse: `Server version: 24.11.1.2557`
> CH-UI: ghcr.io/caioricciuti/ch-ui                                            latest

**Comment by caioricciuti** [comment]
done. 

Schema: 
![Screenshot 2024-12-01 at 19 53 37](https://github.com/user-attachments/assets/e8cc240c-ee91-4a3b-8f5d-1a9b0dcb9c9e)
Dates:
![Screenshot 2024-12-01 at 19 53 59](https://github.com/user-attachments/assets/fd974a86-0b0d-40ee-ac2e-24f6a4e64392)
Better number read (and again dates)
![Screenshot 2024-12-01 at 19 54 27](https://github.com/user-attachments/assets/9f0221e7-fe9b-4ca6-808f-b1afd4253a63)

**Comment by synack-ppetruneac** [comment]
nice! well done!!
