### ISSUE TITLE
Environment variables in docker for connection

### ISSUE THREAD

**Issue by Zerpico** [caioricciuti/ch-ui#5]
### Idea Statement

First of all, I want to express my gratitude for such a wonderful product that I use often. However, there is one thing that I am missing, given that I often use **ch-ui** for testing and writing SQL queries.

It would be great to add support for Docker container variables as connection parameters.
For example:
```
CLICKHOUSE_URL
CLICKHOUSE_USER
CLICKHOUSE_PASS
```

So that when the container starts, you can specify the variables that ch-ui will add as connection settings and you don’t have to enter them manually in the settings

Like this: 
```docker run -p 5521:5521 -e CLICKHOUSE_URL=localhost:5432 -e CLICKHOUSE_USER=default -e CLICKHOUSE_PASS=some_password ghcr.io/caioricciuti/ch-ui:latest```

**Comment by caioricciuti** [comment]
Hey, @Zerpico, hope all is good!

Ut's doable for sure! I'll see if I can implement it soon. 
Thank you for using ch-ui! I'm glad it helps the community!

**Comment by caioricciuti** [comment]
Hey it's added, since the tools uses vite, the env variables start with `VITE_` 

``` bash
docker run -p 5521:5521 \
  -e VITE_CLICKHOUSE_URL=http://your-clickhouse-server:8123 \
  -e VITE_CLICKHOUSE_USER=your-username \
  -e VITE_CLICKHOUSE_PASS=your-password \
  ghcr.io/caioricciuti/ch-ui:latest
```
