### ISSUE TITLE
Run more than one query by highlighting the query 

### ISSUE THREAD

**Issue by c0x65o** [caioricciuti/ch-ui#7]
### Idea Statement

It would be nice for the default click house web UI to be able to run more than one query by highlighting the query. Maybe it does it but I don't know how, but I did look around.

**Comment by caioricciuti** [comment]
Hey, hope all is good! @c0x65o, not sure if I understood it well, like you want to run only the highlighted part of your query? 

On the example below, you want to be able to have `n` queries on the same Tab and run only the highlighted one? 

Like in:

![image](https://github.com/caioricciuti/ch-ui/assets/63287675/cc96c919-c1fc-48a8-aa3b-0cb874e516fd)

**Comment by c0x65o** [comment]
That is correct. That is how Tabix works (other than making you remove the ";" to do it.

**Comment by caioricciuti** [comment]
Ah, ok, I'll try to get it done ASAP! I have an idea on how to approach this feature!

**Comment by caioricciuti** [comment]
Done :)
